export const FRASES = [
    'MAS VALE TARDE QUE NUNCA',
    'A QUIEN MADRUGA NADIE AYUDA',
    'TENGO HAMBRE AQUI HAY FIAMBRE',
    'CHARRANADA',
    'CUANDO EL GRAJO VUELA BAJO HACE UN FRIO DEL CARAJO'
  ]
